name: Android Build & Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build Project
        run: ./gradlew assemble

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run Unit Tests
        run: ./gradlew test


  success_message:

    runs-on: ubuntu-latest

    needs: [ build, test ]

    steps:
      - name: Send Success Message
        run: echo "Build and Test Succeeded"

  assemble_job:
    name: Assemble
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Assemble Debug
        run: ./gradlew assembleDebug